webtalk_init -webtalk_dir E:\\Git\\Thesis_SGM_FPGA\\Zedboard\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-04-24 23:40:12" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3u54dcudv7l1nllofasutqe6ld" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.049 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1556131490778" -context "sdk\\\\bsp/1556131490778"
webtalk_add_data -client sdk -key hwid -value "1553881746517" -context "sdk\\\\bsp/1556131490778"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1556131490778"
webtalk_add_data -client sdk -key apptemplate -value "lwip_udp_perf_client" -context "sdk\\\\bsp/1556131490778"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1556131490778"
webtalk_add_data -client sdk -key uid -value "1556131511358" -context "sdk\\\\application/1556131511358"
webtalk_add_data -client sdk -key hwid -value "1553881746517" -context "sdk\\\\application/1556131511358"
webtalk_add_data -client sdk -key bspid -value "1556131490778" -context "sdk\\\\application/1556131511358"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1556131511358"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1556131511358"
webtalk_add_data -client sdk -key apptemplate -value "lwip_udp_perf_client" -context "sdk\\\\application/1556131511358"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1556131511358"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1556131511358"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1556131511358"
webtalk_add_data -client sdk -key projSize -value "961.0546875" -context "sdk\\\\application/1556131511358"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1556138412710"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1556138412710"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1556138412710"
webtalk_add_data -client sdk -key DebugCount -value "40" -context "sdk\\\\bsp/1556138412710"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1556138412710"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1556138412710"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1556138412710"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1556138412710"
webtalk_transmit -clientid 2082087276 -regid "" -xml E:\\Git\\Thesis_SGM_FPGA\\Zedboard\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\Git\\Thesis_SGM_FPGA\\Zedboard\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\Git\\Thesis_SGM_FPGA\\Zedboard\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
