# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_comp_d_map_0_1/img_proc_hw_comp_d_map_0_1.xci
# IP: The module: 'img_proc_hw_comp_d_map_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_comp_d_map_0_1/constraints/comp_d_map_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_hw_comp_d_map_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_comp_d_map_0_1/img_proc_hw_comp_d_map_0_1.xci
# IP: The module: 'img_proc_hw_comp_d_map_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_comp_d_map_0_1/constraints/comp_d_map_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_hw_comp_d_map_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
