# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/img_proc_hw/img_proc_hw.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_hw || ORIG_REF_NAME==img_proc_hw} -quiet] -quiet

# IP: bd/img_proc_hw/ip/img_proc_hw_processing_system7_0_0/img_proc_hw_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_hw_processing_system7_0_0 || ORIG_REF_NAME==img_proc_hw_processing_system7_0_0} -quiet] -quiet

# IP: bd/img_proc_hw/ip/img_proc_hw_inverse_img_0_0/img_proc_hw_inverse_img_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_hw_inverse_img_0_0 || ORIG_REF_NAME==img_proc_hw_inverse_img_0_0} -quiet] -quiet

# IP: bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/img_proc_hw_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_hw_axi_smc_0 || ORIG_REF_NAME==img_proc_hw_axi_smc_0} -quiet] -quiet

# IP: bd/img_proc_hw/ip/img_proc_hw_rst_ps7_0_100M_0/img_proc_hw_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_hw_rst_ps7_0_100M_0 || ORIG_REF_NAME==img_proc_hw_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/img_proc_hw/ip/img_proc_hw_ps7_0_axi_periph_0/img_proc_hw_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_hw_ps7_0_axi_periph_0 || ORIG_REF_NAME==img_proc_hw_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/img_proc_hw/ip/img_proc_hw_auto_pc_0/img_proc_hw_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_hw_auto_pc_0 || ORIG_REF_NAME==img_proc_hw_auto_pc_0} -quiet] -quiet

# XDC: bd/img_proc_hw/img_proc_hw_ooc.xdc
