# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.cache/wt [current_project]
set_property parent.project_path E:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths e:/Git/Thesis_SGM_FPGA [current_project]
update_ip_catalog
set_property ip_output_repo e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib E:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/hdl/img_proc_hw_wrapper.vhd
add_files E:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/img_proc_hw.bd
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_processing_system7_0_0/img_proc_hw_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_2/bd_0020_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_3/bd_0020_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_4/bd_0020_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_5/bd_0020_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_6/bd_0020_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_10/bd_0020_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_11/bd_0020_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_12/bd_0020_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_13/bd_0020_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_14/bd_0020_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_15/bd_0020_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_19/bd_0020_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_20/bd_0020_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_21/bd_0020_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_22/bd_0020_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_23/bd_0020_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_24/bd_0020_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_25/bd_0020_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_26/bd_0020_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_27/bd_0020_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_28/bd_0020_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_29/bd_0020_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_30/bd_0020_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_rst_ps7_0_100M_0/img_proc_hw_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_rst_ps7_0_100M_0/img_proc_hw_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_rst_ps7_0_100M_0/img_proc_hw_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_comp_d_map_0_1/constraints/comp_d_map_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_xbar_0/img_proc_hw_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_auto_pc_1/img_proc_hw_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_auto_pc_0/img_proc_hw_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/img_proc_hw_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top img_proc_hw_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef img_proc_hw_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file img_proc_hw_wrapper_utilization_synth.rpt -pb img_proc_hw_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
