# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/Git/Thesis_SGM_FPGA/hw_sgm/solution1/impl/vhdl/comp_d_map.xdc

# Block Designs: bd/bd_0/bd_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0} -quiet] -quiet

# IP: bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_hls_inst_0 || ORIG_REF_NAME==bd_0_hls_inst_0} -quiet] -quiet

# XDC: bd/bd_0/bd_0_ooc.xdc
