# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/img_proc_hw_axi_smc_0.xci
# IP: The module: 'img_proc_hw_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/bd_0020.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_0/bd_0020_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_2/bd_0020_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_3/bd_0020_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_4/bd_0020_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_5/bd_0020_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_6/bd_0020_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_7/bd_0020_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_8/bd_0020_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_9/bd_0020_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_10/bd_0020_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_11/bd_0020_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_12/bd_0020_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_5/bd_0020_s00a2s_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_6/bd_0020_sarn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_7/bd_0020_srn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_8/bd_0020_sawn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_9/bd_0020_swn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_10/bd_0020_sbn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_11/bd_0020_m00s2a_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_hw_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/img_proc_hw_axi_smc_0.xci
# IP: The module: 'img_proc_hw_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/bd_0020.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_0/bd_0020_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_2/bd_0020_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_3/bd_0020_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_4/bd_0020_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_5/bd_0020_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_6/bd_0020_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_7/bd_0020_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_8/bd_0020_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_9/bd_0020_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_10/bd_0020_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_11/bd_0020_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_12/bd_0020_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_5/bd_0020_s00a2s_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_6/bd_0020_sarn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_7/bd_0020_srn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_8/bd_0020_sawn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_9/bd_0020_swn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_10/bd_0020_sbn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_11/bd_0020_m00s2a_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_hw_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
