# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/img_proc_hw_axi_smc_0.xci
# IP: The module: 'img_proc_hw_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/bd_0020.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_0/bd_0020_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_2/bd_0020_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_3/bd_0020_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_4/bd_0020_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_5/bd_0020_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_6/bd_0020_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_7/bd_0020_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_8/bd_0020_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_9/bd_0020_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_10/bd_0020_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_11/bd_0020_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_12/bd_0020_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_13/bd_0020_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_14/bd_0020_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_15/bd_0020_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_16/bd_0020_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_17/bd_0020_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_18/bd_0020_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_19/bd_0020_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_20/bd_0020_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_21/bd_0020_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_22/bd_0020_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_23/bd_0020_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_24/bd_0020_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_25/bd_0020_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_26/bd_0020_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_27/bd_0020_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_28/bd_0020_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_29/bd_0020_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_30/bd_0020_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_31/bd_0020_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_hw_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_2/bd_0020_arsw_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_3/bd_0020_rsw_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_4/bd_0020_awsw_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_5/bd_0020_wsw_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_6/bd_0020_bsw_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_10/bd_0020_s03a2s_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_11/bd_0020_sarn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_12/bd_0020_srn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_13/bd_0020_sawn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_14/bd_0020_swn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_15/bd_0020_sbn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_19/bd_0020_s04a2s_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_20/bd_0020_sarn_1_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_21/bd_0020_srn_1_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_22/bd_0020_sawn_1_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_23/bd_0020_swn_1_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_24/bd_0020_sbn_1_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_25/bd_0020_m00s2a_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_26/bd_0020_m00arn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_27/bd_0020_m00rn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_28/bd_0020_m00awn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_29/bd_0020_m00wn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_30/bd_0020_m00bn_0_ooc.xdc

# IP: E:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/img_proc_hw_axi_smc_0.xci
# IP: The module: 'img_proc_hw_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/bd_0020.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_0/bd_0020_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_2/bd_0020_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_3/bd_0020_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_4/bd_0020_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_5/bd_0020_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_6/bd_0020_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_7/bd_0020_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_8/bd_0020_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_9/bd_0020_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_10/bd_0020_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_11/bd_0020_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_12/bd_0020_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_13/bd_0020_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_14/bd_0020_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_15/bd_0020_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_16/bd_0020_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_17/bd_0020_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_18/bd_0020_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_19/bd_0020_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_20/bd_0020_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_21/bd_0020_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_22/bd_0020_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_23/bd_0020_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_24/bd_0020_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_25/bd_0020_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_26/bd_0020_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_27/bd_0020_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_28/bd_0020_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_29/bd_0020_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_30/bd_0020_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_31/bd_0020_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_hw_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_1/bd_0020_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_2/bd_0020_arsw_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_3/bd_0020_rsw_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_4/bd_0020_awsw_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_5/bd_0020_wsw_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_6/bd_0020_bsw_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_10/bd_0020_s03a2s_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_11/bd_0020_sarn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_12/bd_0020_srn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_13/bd_0020_sawn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_14/bd_0020_swn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_15/bd_0020_sbn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_19/bd_0020_s04a2s_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_20/bd_0020_sarn_1_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_21/bd_0020_srn_1_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_22/bd_0020_sawn_1_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_23/bd_0020_swn_1_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_24/bd_0020_sbn_1_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_25/bd_0020_m00s2a_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_26/bd_0020_m00arn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_27/bd_0020_m00rn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_28/bd_0020_m00awn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_29/bd_0020_m00wn_0_ooc.xdc

# XDC: e:/Git/Thesis_SGM_FPGA/zebdoard_sgm/zebdoard_sgm.srcs/sources_1/bd/img_proc_hw/ip/img_proc_hw_axi_smc_0/bd_0/ip/ip_30/bd_0020_m00bn_0_ooc.xdc
